<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

    public function listByCustomer($customer)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.customer = :customer')
            ->setParameter('customer', $customer)
            ->getQuery();

        return $qb->execute();


    }
}
